// Do not edit. This file is machine generated by the Resource DLL Wizard.

library ConsultaRemota;

{ITE} {LCID:0000240A:0000240A} {}
{ITE} {DFMFileType} {Archivos\sistemas\units\UnitPantallaProgreso.dfm}
{ITE} {DFMFileType} {vcl\DBLOGDLG.dfm}
{ITE} {DFMFileType} {vcl\DBPWDLG.dfm}
{ITE} {DFMFileType} {UnitConsultaRemota.dfm}
{ITE} {RCFileType} {ConsultaRemota_DRC.rc}

{$R 'Archivos\sistemas\units\UnitPantallaProgreso.dfm' frmProgreso:TForm}
{$R 'vcl\DBLOGDLG.dfm' LoginDialog:TForm(Form)}
{$R 'vcl\DBPWDLG.dfm' PasswordDialog:TForm(Form)}
{$R 'UnitConsultaRemota.dfm' frmConsultaRemota:TForm}
{$R 'ConsultaRemota_DRC.res' 'ConsultaRemota_DRC.rc'}

{$E ESO}

begin
end.