program Nomina;

uses
  Forms,
  UnitEmpleado in 'Unit\UnitEmpleado.pas' {FrmEmpleado},
  UnitDatamodulo in 'Unit\UnitDatamodulo.pas' {DataGeneral: TDataModule},
  UnitLogin in 'Unit\UnitLogin.pas' {login},
  UnitPrincipal in 'Unit\UnitPrincipal.pas' {FrMain},
  Consts in 'Unit\Consts.pas',
  Unitdata in 'Unit\Unitdata.pas' {frmdata: TDataModule},
  UnitQuerys in 'Unit\UnitQuerys.pas' {DataQuerys: TDataModule},
  UnitEntidad in 'Unit\UnitEntidad.pas' {FrmEntidad},
  UnitDatosempleado in 'Unit\UnitDatosempleado.pas' {Frmempleado1},
  UnitPrestacion in 'Unit\UnitPrestacion.pas' {FrmPrestacion},
  UnitdataQuerys in 'Unit\UnitdataQuerys.pas' {FrmQuerys: TDataModule},
  UnitVacaciones in 'Unit\UnitVacaciones.pas' {FrmVacaciones},
  UnitDescuento in 'Unit\UnitDescuento.pas' {FrmDescuentos},
  UnitCartera in 'Unit\UnitCartera.pas' {FrmCartera},
  UnitHorasExtras in 'Unit\UnitHorasExtras.pas' {FrmHorasExtras},
  UnitNomina in 'Unit\UnitNomina.pas' {FrmNomina},
  UnitImpresion in 'Unit\UnitImpresion.pas' {FrmImpresion},
  UnitRealizaNomina in 'Unit\UnitRealizaNomina.pas' {FrmRealizaNomina},
  UnitBuscarTexto in '..\Activos\unit\UnitBuscarTexto.pas' {frmBuscarTexto},
  Unitcuentasporcobrar in 'Unit\Unitcuentasporcobrar.pas' {FrmCuentasPorCobrar},
  Unitprogreso in 'Unit\Unitprogreso.pas' {FrmProgreso},
  UnitFondos in 'Unit\UnitFondos.pas' {FrmFondos},
  UnitRepCartera in 'Unit\UnitRepCartera.pas' {FrmRepCartera},
  UnitPrimas in 'Unit\UnitPrimas.pas' {FrmPrimas},
  UnitNovedades in 'Unit\UnitNovedades.pas' {FrmActualizar},
  UnitAgencias in 'Unit\UnitAgencias.pas' {FrmAgencias},
  UnitObligacionesLab in 'Unit\UnitObligacionesLab.pas' {FrmObligacionLaboral},
  UnitActualizacausacion in 'Unit\UnitActualizacausacion.pas' {FrmActualizaCausacion},
  UnitPantallaProgreso in 'Unitv\UnitPantallaProgreso.pas' {frmProgresos},
  UnitRecupera in 'Unit\UnitRecupera.pas' {FrmRecupera},
  UnitEliminaHoras in 'Unit\UnitEliminaHoras.pas' {FrmReversar},
  UnitRetefuente in 'Unit\UnitRetefuente.pas' {FrmReteFuente},
  UnitEliminaEmpleado in 'Unit\UnitEliminaEmpleado.pas' {FrmEliminaEmpleado},
  UnitPagoPrimas in 'Unit\UnitPagoPrimas.pas' {FrmPagoPrimas},
  UnitVistaPreliminar in 'Unitv\UnitVistaPreliminar.pas' {frmVistaPreliminar},
  UnitModDescuentos in 'Unit\UnitModDescuentos.pas' {FrmModDescuentos},
  UnitDbProgres in 'Unitv\UnitDbProgres.pas' {FrmDbProgres},
  UnitDb in 'Unitv\UnitDb.pas' {frmDB},
  UnitRecuperaHoras in 'Unit\UnitRecuperaHoras.pas' {FrmRecuperaHora},
  UnitCausacionCesantias in 'Unit\UnitCausacionCesantias.pas' {FrmCausacionCesantias},
  UnitActualizaPension in 'Unit\UnitActualizaPension.pas' {FrmActualizaPension},
  Unit_DmComprobante in '..\..\units\Unit_DmComprobante.pas' {DmComprobante: TDataModule},
  UnitdmColocacion in 'otraunit\UnitdmColocacion.pas' {dmColocacion: TDataModule},
  UnitdmGeneral in 'Unit\UnitdmGeneral.pas' {dmGeneral: TDataModule},
  UnitPension in 'Unit\UnitPension.pas' {FrmPension},
  Unit_Comprobante in '..\..\units\Unit_Comprobante.pas' {frmComprobante},
  digitacuenta in '..\..\units\digitacuenta.pas' {digita},
  Unit_Mantenimientopuc in '..\..\units\Unit_Mantenimientopuc.pas' {frmMantenimientopuc},
  Unit_Dmpuc in '..\..\units\Unit_Dmpuc.pas' {Dmpuc: TDataModule},
  Unit_BuscarCodigo in '..\..\units\Unit_BuscarCodigo.pas' {frmBuscarCodigo},
  Unit_BuscarClave in '..\..\units\Unit_BuscarClave.pas' {frmBuscarClave},
  UnitCreaciondePersona in '..\..\units\UnitCreaciondePersona.pas' {frmCreacionPersona},
  UnitdmPersona in '..\..\units\UnitdmPersona.pas' {dmPersona: TDataModule},
  UnitTomarFoto in '..\..\units\UnitTomarFoto.pas' {frmTomarFoto},
  UnitTomaHuella in '..\..\units\UnitTomaHuella.pas' {frmRegister},
  Videocap in '..\..\units\Videocap.pas',
  VFW in '..\..\units\VfW.pas',
  UnitVerificarHuella in '..\..\units\UnitVerificarHuella.pas' {frmVerify},
  Unit_buscarcomprobante in '..\..\units\Unit_buscarcomprobante.pas' {frmbuscarcomprobante},
  UnitTipoImpresion in '..\..\units\UnitTipoImpresion.pas' {frmTipoImpresion},
  UnitCancelar in 'Unit\UnitCancelar.pas' {FrmCancelar},
  UnitDescuentoExtra in 'Unit\UnitDescuentoExtra.pas' {FrmDescuentoExtra},
  UnitRegistraCol in 'Unit\UnitRegistraCol.pas' {FrmDesmarcarCol},
  UnitFormato in 'Unit\UnitFormato.pas' {FrmFormato},
  UnitCambiosFun in '..\..\units\UnitCambiosFun.pas' {FrmCambiosFun},
  UnitBuscarCiiu in '..\..\units\UnitBuscarCiiu.pas' {frmBuscarCIIU},
  UnitCreacionPersonaIndependiente in '..\..\units\UnitCreacionPersonaIndependiente.pas' {frmCreacionPersonaIndependiente},
  UnitExportar in 'Unit\UnitExportar.pas' {FrmExportarPagos},
  UnitGlobales in '..\..\Globales\UnitGlobales.pas',
  UnitGlobalesCol in '..\..\Globales\UnitGlobalesCol.pas',
  DataSetToExcel in '..\..\units\DataSetToExcel.pas',
  UnitGlobal in 'Unit\UnitGlobal.pas',
  UnitCausacion in 'Unit\UnitCausacion.pas' {FrmCausacion},
  UnitEstudios in 'Unit\UnitEstudios.pas' {FrmEstudios},
  UnitGestionEstudios in 'Unit\UnitGestionEstudios.pas' {FrmGestionEstudios},
  UnitGuardaImagen in '..\..\Units\UnitGuardaImagen.pas',
  UnitIngresaLibranza in 'Unit\UnitIngresaLibranza.pas' {FrmIngresaLibranza};

{$R *.res}

begin
  Application.Initialize;
  Application.Title := 'Sistema de Nomina Crediservir Ltda.';
  Application.CreateForm(TFrMain, FrMain);
  Application.Run;
end.
