program Fundacion;

uses
  Forms,
  Consts in '..\..\Units\Consts.pas',
  UnitPrincipal in 'Unit\UnitPrincipal.pas' {FrMain},
  UnitDatamodulo in 'Unit\UnitDatamodulo.pas' {DataGeneral: TDataModule},
  Unitdata in 'Unit\Unitdata.pas' {frmdata: TDataModule},
  UnitLogin in 'Unit\UnitLogin.pas' {login},
  UnitPrograma in 'Unit\UnitPrograma.pas' {FrmPrograma},
  UnitBeneficiario in 'Unit\UnitBeneficiario.pas' {FrmBeneficiario},
  UnitdataQuerys in 'Unit\UnitdataQuerys.pas' {FrmQuerys: TDataModule},
  UnitQuerys in 'Unit\UnitQuerys.pas' {DataQuerys: TDataModule},
  Unitprogreso in 'Unit\Unitprogreso.pas' {FrmProgreso},
  UnitConvenios in 'Unit\UnitConvenios.pas' {FrmConvenio},
  UnitBusca in 'Unit\UnitBusca.pas' {FrmBuscar},
  UnitBuscarTexto in '..\Activos\unit\UnitBuscarTexto.pas' {frmBuscarTexto},
  UnitAfiliacion in 'Unit\UnitAfiliacion.pas' {FrmAfiliacion},
  UnitCarnet in 'Unit\UnitCarnet.pas' {FrmCarnet},
  UnitCarnetBene in 'Unit\UnitCarnetBene.pas' {FrmCarnetBene},
  UnitPantallaProgreso in 'Unit\UnitPantallaProgreso.pas' {frmProgresos},
  UnitCredito in 'Unit\UnitCredito.pas' {FrmCredito},
  Unittipo in 'Unit\Unittipo.pas' {FrmTipo},
  UnitImpresion in 'Unit\UnitImpresion.pas' {FrmImpresion},
  UnitNuevaAfiliacion in 'Unit\UnitNuevaAfiliacion.pas' {FrmNuevaAfiliacion},
  UnitActualizaFecha in 'Unit\UnitActualizaFecha.pas' {FrmActualizafecha},
  UnitActualizaBene in 'Unit\UnitActualizaBene.pas' {FrmActualizaBene},
  UnitFechaven in 'Unit\UnitFechaven.pas' {FrmFechaven},
  UnitEps in 'Unit\UnitEps.pas' {FrmEps},
  UnitAfiliacionEps in 'Unit\UnitAfiliacionEps.pas' {FrmAfiliacionEps},
  UnitActualiza in 'Unit\UnitActualiza.pas' {FrmActualizarD},
  UnitReportes in 'Unit\UnitReportes.pas' {FrmReportes},
  UnitReversar in 'Unit\UnitReversar.pas' {FrmReversar},
  UnitTipocapacitacion in 'Unit\UnitTipocapacitacion.pas' {FrmTipocapacitacion},
  UnitCapacitaciones in 'Unit\UnitCapacitaciones.pas' {FrmCapacitaciones},
  UnitRegistropas in 'Unit\UnitRegistropas.pas' {FrmRegistropas},
  UnitRegistrocap in '..\Activos\unit\UnitRegistrocap.pas' {FrmRegistrocap},
  Unitrepcapacitaciones in 'Unit\Unitrepcapacitaciones.pas' {FrmRepcapacitaciones},
  Unitrepcapacitacion in 'Unit\Unitrepcapacitacion.pas' {FrmRepCapacitacion},
  UnitCapacitacioncon in 'Unit\UnitCapacitacioncon.pas' {FrmCapacitacionCon},
  UnitConferencista in 'Unit\UnitConferencista.pas' {FrmConferencista},
  UnitConsulta in 'Unit\UnitConsulta.pas' {FrmConsulta},
  UnitRepBeneficiarios in 'Unit\UnitRepBeneficiarios.pas' {FrmRepBeneficiarios},
  UnitAsociadoTitular in 'Unit\UnitAsociadoTitular.pas' {FrmAsociadoTitular},
  UnitRepVentas in 'Unit\UnitRepVentas.pas' {FrmRepVentas},
  UnitActCarne in 'Unit\UnitActCarne.pas' {FrmActCarne},
  UnitGrupo in 'Unit\UnitGrupo.pas' {FrmGrupo},
  UnitAsistencia in 'Unit\UnitAsistencia.pas' {FrmAsistencia},
  UnitReEps in 'Unit\UnitReEps.pas' {FrmReEps},
  UnitActaualizaBene in 'Unit\UnitActaualizaBene.pas' {FrmActaulizaBene},
  UnitGlobal in 'Unit\UnitGlobal.pas',
  UnitReconfirmar in 'UnitReconfirmar.pas' {frmReconfirmar},
  UnitActualizanit in 'Unit\UnitActualizanit.pas' {FrmActualizanit},
  UnitVistaPreliminar in 'otraunit\UnitVistaPreliminar.pas' {frmVistaPreliminar},
  UnitEliCapacitacion in 'Unit\UnitEliCapacitacion.pas' {FrmElicapacitacion},
  UnitRequisitoscre in '..\Solicitud Creditos\Unit\UnitRequisitoscre.pas' {FrmRequisitoscre},
  UnitRequisitoNuevo in '..\Solicitud Creditos\Unit\UnitRequisitoNuevo.pas' {FrmRequisitoNuevo},
  Unit_DmComprobante in '..\..\units\Unit_DmComprobante.pas' {DmComprobante: TDataModule},
  UnitdmColocacion in '..\..\units\UnitdmColocacion.pas' {dmColocacion: TDataModule},
  UnitCreaciondePersona in '..\..\units\UnitCreaciondePersona.pas' {frmCreacionPersona},
  UnitdmPersona in '..\..\units\UnitdmPersona.pas' {dmPersona: TDataModule},
  UnitTomarFoto in '..\..\units\UnitTomarFoto.pas' {frmTomarFoto},
  UnitTomaHuella in '..\..\units\UnitTomaHuella.pas',
  UnitVerificarHuella in '..\..\units\UnitVerificarHuella.pas',
  UnitImpresionCaptacion in '..\..\units\UnitImpresionCaptacion.pas' {frmImpresionCaptacion},
  UnitdmCaptacion in '..\..\units\UnitdmCaptacion.pas' {dmCaptacion: TDataModule},
  UnitDescObservacion in '..\Solicitud Creditos\Unit\UnitDescObservacion.pas' {FrmDescObsrevacion},
  UnitBuscaSolicitud in '..\Solicitud Creditos\Fundacion\UnitBuscaSolicitud.pas' {FrmBuscaSolicitud},
  FR_ChBox in '..\Archivos de programa\FastReports\FastReport\source\FR_ChBox.pas',
  UnitEstadoSolicitud in '..\Solicitud Creditos\Fundacion\UnitEstadoSolicitud.pas' {FrmEstadoSolicitud},
  UnitEjemplo in 'Unit\UnitEjemplo.pas' {FrmEjemplo},
  UnitRiesgos in '..\..\units\UnitRiesgos.pas' {FrmRiesgos},
  VFW in '..\..\units\VfW.pas',
  Videocap in '..\..\units\Videocap.pas',
  UnitdmGeneral in 'Unit\UnitdmGeneral.pas' {dmGeneral: TDataModule},
  UnitConyuge in '..\..\units\UnitConyuge.pas' {FrmConyuge},
  UnitConsultaProductos in 'Unit\UnitConsultaProductos.pas' {frmConsultaProductos},
  UnitRelacionChequesEnCanje in '..\..\Units\UnitRelacionChequesEnCanje.pas' {frmRelacionChequesEnCanje},
  UnitExtractoColocacion in '..\..\Units\UnitExtractoColocacion.pas' {FrmExtractoColocacion},
  UnitObservacionesCambioEstado in '..\..\Units\UnitObservacionesCambioEstado.pas' {frmObservacionesCambioEstado},
  UnitControldeObservaciones in '..\..\Units\UnitControldeObservaciones.pas' {frmControldeObservaciones},
  UnitRegistrarObservacion in '..\..\Units\UnitRegistrarObservacion.pas' {frmRegistrarObservacion},
  UnitExtractoCredito in '..\..\Units\UnitExtractoCredito.pas' {frmExtractoCredito},
  UnitCambiosFun in '..\..\units\UnitCambiosFun.pas' {FrmCambiosFun},
  UnitPlanoCredivida in '..\..\Units\UnitPlanoCredivida.pas' {FrmPlanoCredivida},
  DataSetToExcel in '..\..\Units\DataSetToExcel.pas',
  UnitCredividasVencidos in 'Unit\UnitCredividasVencidos.pas' {FrmCredividasVencidos},
  UnitClaseXml in '..\Modulo Tarjeta Debito\Units\UnitClaseXml.pas',
  UnitDmSolicitud in '..\..\Units\UnitDmSolicitud.pas' {DmSolicitud: TDataModule},
  UnitBuscarCiiu in '..\..\Units\UnitBuscarCiiu.pas' {frmBuscarCIIU},
  UnitCreacionPersonaIndependiente in '..\..\Units\UnitCreacionPersonaIndependiente.pas' {frmCreacionPersonaIndependiente},
  UnitVida in '..\..\Units\UnitVida.pas' {FrmVida},
  UnitBuscarPersona in '..\..\Units\UnitBuscarPersona.pas' {frmBuscarPersona},
  UnitConsultaExtractoCaptacion in 'Unit\UnitConsultaExtractoCaptacion.pas' {frmConsultaExtractoCaptacion},
  UnitGlobalesCol in '..\..\Globales\UnitGlobalesCol.pas',
  UnitGlobales in '..\..\Globales\UnitGlobales.pas',
  UnitInformacion in 'Unit\UnitInformacion.pas' {FrmInformacion},
  UnitGuardaImagen in '..\..\Units\UnitGuardaImagen.pas';

{$R *.res}

begin
  Application.Initialize;
  Application.Title := 'Fundación Crediservir Ltda';
  Application.CreateForm(TdmGeneral, dmGeneral);
  Application.CreateForm(TFrMain, FrMain);
  Application.Run;
end.
